on:
  push:
jobs:
   build: 
     runs-on: ubuntu-latest
     steps: 
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: get file changes
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
          
# git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
