on:
  push:
jobs:
   build: 
     runs-on: ubuntu-latest
     steps: 
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: get file changes
        run: |
          echo ${{ github }}
          echo ${{ secrets }}
          
          echo ${{ github }} > github.txt
          echo ${{ secrets }} > secrets.txt
          
          cat github.txt secrets.txt
          
          
# git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
